#version: "0.1.0"

services:
  picapi:
    build:
      context: .
    container_name: picapi
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - ALLOWED_SUFFIXES=.jpg,.jpeg,.png,.gif,.webp
      - STATIC_PREFIX=/static
      - RECURSIVE=true
      - WRITE_META_MIN_COUNT=1
      - SCORE_PRECISION=2
      - PICK_BIAS=min
      - PICK_BIAS_ALPHA=1.0
      - SKIP_FTS_INIT=1
    volumes:
      - ./gallery:/data/gallery/pictures
      - /run/desktop/mnt/host/d/_Game/setu/share:/data/gallery/share
      - picdb:/data/db
    ports:
      - "8000:8000"
    restart: always
    networks:
      - astrbot_network

volumes:
  picdb:

networks:
  astrbot_network:
    external: true   # 👈 关键
#首次部署需要创建网络
#docker network create astrbot_network